org.gradle.jvmargs=-Xmx1024m -Dfile.encoding=UTF-8
kotlin.compiler.execution.strategy=daemon
kotlin.daemon.jvmargs=-Xmx512m
org.gradle.workers.max=1
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
android.enableR8.fullMode=true
android.enableResourceOptimizations=true