org.gradle.jvmargs=-Xmx1536m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.java.home=/home/saif/jdk17
kotlin.compiler.execution.strategy=in-process
org.gradle.workers.max=2
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
android.enableR8.fullMode=true
android.enableResourceOptimizations=true